backend:
  # Use netlify identity as backend
  branch: main # Branch to update (optional; defaults to main)
  name: git-gateway
  repo: aryansrivastav1/gsdp-cms-website
media_folder: "/media/"
public_folder: "/media/"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  # Post Collection
  - name: "post"
    label: "Post"
    folder: "posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]

  # Sidebar Collection
  - name: "sidebar"
    label: "Sidebar"
    editor:
      preview: false
    files:
      - label: "Introduction"
        name: "side_head"
        file: "_data/sidebar_head.yml"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Content", name: "content", widget: "string" }
      - label: "Contact Details"
        name: "contact_details"
        file: "_data/contact.yml"
        fields:
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Google Maps", name: "map", widget: "string" }
          - { label: "Google Maps URL", name: "map_url", widget: "string" }
          - { label: "Primary Number", name: "pri_number", widget: "string" }
          - { label: "Primary Number URL", name: "pri_number_url", widget: "string" }
          - { label: "Secondary Number", name: "sec_number", widget: "string" }
          - { label: "Secondary Number URL", name: "sec_number_url", widget: "string" }
          - { label: "Consultation Email", name: "consult_email", widget: "string" }
          - { label: "Consultation Email URL", name: "consult_email_url", widget: "string" }
          - { label: "Information Email", name: "info_email", widget: "string" }
          - { label: "Information Email URL", name: "info_email_url", widget: "string" }
          - { label: "With-us Email", name: "withus_email", widget: "string" }
          - { label: "With-us Email URL", name: "withus_email_url", widget: "string" }
      - label: "Quick Links"
        name: "quick_links"
        file: "_data/quick_links.yml"
        fields:
          - { label: "Title", name: "stories", widget: "string" }
          - { label: "URL", name: "stories_url", widget: "string" }
          - { label: "Title", name: "about_us", widget: "string" }
          - { label: "URL", name: "about_us_url", widget: "string" }
          - { label: "Title", name: "owners", widget: "string" }
          - { label: "URL", name: "owners_url", widget: "string" }
          - { label: "Title", name: "builders", widget: "string" }
          - { label: "URL", name: "builders_url", widget: "string" }
          - { label: "Title", name: "students", widget: "string" }
          - { label: "URL", name: "students_url", widget: "string" }

  # Settings Collection
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - label: "Navigation Links"
        name: "nav_links"
        file: "_data/navigation.yml"
        fields:
          - { label: "Nav Title", name: "everything", widget: "string" }
          - { label: "URL", name: "everything_url", widget: "string" }
          - { label: "Nav Title", name: "services", widget: "string" }
          - { label: "URL", name: "services_url", widget: "string" }
          - { label: "Nav Title", name: "project", widget: "string" }
          - { label: "URL", name: "project_url", widget: "string" }
          - { label: "Nav Title", name: "about", widget: "string" }
          - { label: "URL", name: "about_url", widget: "string" }
          - { label: "Nav Title", name: "ph_number", widget: "string" }
          - { label: "URL", name: "ph_number_url", widget: "string" }
